export const MENU_TOPIC_GET_REQUEST = 'MENU_TOPIC_GET_REQUEST';
export const MENU_TOPIC_GET_SUCCESS = 'MENU_TOPIC_GET_SUCCESS';
export const MENU_TOPIC_GET_FAIL = 'MENU_TOPIC_GET_FAIL';

export const MENU_COURSE_GET_REQUEST = 'MENU_COURSE_GET_REQUEST';
export const MENU_COURSE_GET_SUCCESS = 'MENU_COURSE_GET_SUCCESS';
export const MENU_COURSE_GET_FAIL = 'MENU_COURSE_GET_FAIL';

export const MENU_COURSE_DETAIL_REQUEST = 'MENU_COURSE_DETAIL_REQUEST';
export const MENU_COURSE_DETAIL_SUCCESS = 'MENU_COURSE_DETAIL_SUCCESS';
export const MENU_COURSE_DETAIL_FAIL = 'MENU_COURSE_DETAIL_FAIL';

export const ENROLL_COURSE_POST_REQUEST = 'ENROLL_COURSE_POST_REQUEST';
export const ENROLL_COURSE_POST_SUCCESS = 'ENROLL_COURSE_POST_SUCCESS';
export const ENROLL_COURSE_POST_FAIL = 'ENROLL_COURSE_POST_FAIL';